import { GoogleGenAI } from "@google/genai";

const apiKey = process.env.API_KEY;
// Using the specified Nano banana powered model
const MODEL_NAME = 'gemini-2.5-flash-image';

export const generateHeadshot = async (
  originalImageBase64: string,
  stylePrompt: string
): Promise<string> => {
  if (!apiKey) {
    throw new Error("API Key is missing. Please check your environment variables.");
  }

  const ai = new GoogleGenAI({ apiKey });

  // Clean the base64 string if it contains the data URL prefix
  const cleanBase64 = originalImageBase64.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              data: cleanBase64,
              mimeType: 'image/jpeg', // Assuming jpeg/png for upload
            },
          },
          {
            text: `Transform this image into a professional headshot. ${stylePrompt}. High resolution, photorealistic, 4k. Maintain the person's identity but improve lighting and background.`
          },
        ],
      },
      // Note: responseMimeType and responseSchema are NOT supported for this model
    });

    let generatedImageBase64 = '';

    if (response.candidates && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          generatedImageBase64 = part.inlineData.data;
          break; // Found the image
        }
      }
    }

    if (!generatedImageBase64) {
      throw new Error("No image generated by the model.");
    }

    return `data:image/jpeg;base64,${generatedImageBase64}`;

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

export const editHeadshot = async (
  currentImageBase64: string,
  editPrompt: string
): Promise<string> => {
  if (!apiKey) {
    throw new Error("API Key is missing.");
  }

  const ai = new GoogleGenAI({ apiKey });
  const cleanBase64 = currentImageBase64.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              data: cleanBase64,
              mimeType: 'image/jpeg',
            },
          },
          {
            text: `Edit this image: ${editPrompt}. Maintain high quality and photorealism.`
          },
        ],
      },
    });

    let generatedImageBase64 = '';

    if (response.candidates && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          generatedImageBase64 = part.inlineData.data;
          break;
        }
      }
    }

    if (!generatedImageBase64) {
      throw new Error("No image generated by the model during edit.");
    }

    return `data:image/jpeg;base64,${generatedImageBase64}`;

  } catch (error) {
    console.error("Gemini API Edit Error:", error);
    throw error;
  }
};
